---
title: Cousin Paul
timezone: America/Chicago
collections:
  artists:
    title: Artists
    output: true
    Artist Title: Artist
    Portfolio Images:
    - 
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
- scope:
    path: blog
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: artists
  values:
    layout: artist
    Artist Title: Artist
    Email:
    Hours:
    Portfolio Images:
    -
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- README.md
