title: Cousin Paul
timezone: America/Chicago
permalink: pretty

collections:
  artists:
    title: Artists
    output: true
    permalink: /artist/:path/
defaults:
- scope:
    path: ""
    type: pages
  values:
    layout: default
    header_img_class: default
- scope:
    path: ""
    type: artists
  values:
    layout: artist
    header_img_class: default
    _order: 0

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- README.md
