backend:
 name: git-gateway

media_folder: 'asset/img/upload'
public_folder: '/asset/img/upload'

collections:

  - name: 'artists'
    label: 'Artists'
    folder: '_artists'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Order', name: 'order', widget: 'number', min: 0, max: 99, default: 99, valueType: int }
      - { label: 'Artist Name', name: 'title', widget: 'string' }
      - { label: 'Artist Title', name: 'artist_title', widget: 'string' }
      - { label: 'Artist Image', name: 'artist_image', widget: 'image', required: false }
      - label: 'Portfolio Images'
        name: 'portfolio_images'
        widget: 'list'
        required: false
        field:
          - { label: Portfolio Image, name: portfolio_image, widget: image, required: false }
      - { label: 'Email', name: 'email', widget: 'string', required: false }
      - { label: 'Facebook', name: 'facebook', widget: 'string', required: false }
      - { label: 'Instagram', name: 'instagram', widget: 'string', required: false }
      - { label: 'Hours', name: 'hours', widget: 'markdown', required: false }

  - label: 'Pages'
    name: 'pages'
    files:

      - label: 'About'
        name: 'about'
        file: 'about.md'
        fields:
          - { label: Title, name: title, widget: string }

      - label: 'Artists'
        name: 'artists'
        file: 'artists.md'
        fields:
          - { label: Title, name: title, widget: string }

      - label: 'Contact'
        name: 'contact'
        file: 'contact.md'
        fields:
          - { label: Title, name: title, widget: string }

      - label: 'FAQ'
        name: 'faq'
        file: 'faq.md'
        fields:
          - { label: Title, name: title, widget: string }
          - { label: FAQ, name: faq, widget: markdown }

      - label: 'Gallery'
        name: 'gallery'
        file: 'gallery.md'
        fields:
          - { label: Title, name: title, widget: string }
